name: test
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hello"
        shell: bash
  new:
    runs-on: ubuntu-latest
    steps:
      - run: python inside.py

  